apiVersion: skaffold/v3
kind: Config
metadata:
  name: go-heif-api

build:
  artifacts:
    - image: asia-southeast1-docker.pkg.dev/saruberoz/parkee-app/staging/go-heif-api
      context: .

manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
deploy:
  kubeContext: "gke_saruberoz_asia-southeast1-a_parkee-ms-stag-cluster"
